###DroneServie config
isUseDroneService=false
deviceUseRTCP=true
linkhubProfilePath=D:/jiangcheng/linkhub/profiles
mavlogWorkspace=D:/drone-server/mavlogs
linkhubIP=127.0.0.1
#Timeout of connecting drones.Unit is second.
connectTimeout=30
#Session idle time.Unit is second.
idleTime=600
#Session timeout.Unit is second.
sessionTimeout=30
#The time span of checking drones.Unit is second.
checkDroneTime=30
#The systemId of gcs.
gcsSystemId=255
###CommandService Config
cmdTcpMode=true
cmdTcpPort=60000
cmdUdpMode=true
cmdUdpPort=60000
#The time span of sending heartbeat.Unit is millisecond.
tsSendHeartbeat=1000
isTcpServerSendHeartbeat=true
isUdpServerSendHeartbeat=false
###Joystick service config
isUseJoystickService=false
joystickConfigFile=x56Left.properties,x56Right.properties

