package com.hkxx.drone;

public class CommandType {
    public static final String UPLOAD_TASK = "upload_task";
    public static final String START_MISSION = "start_mission";
    public static final String GO_HOME = "go_home";
    public static final String PAUSE_MISSION = "pause_mission";
    public static final String RESUME_MISSION = "resume_mission";
    public static final String STOP_MISSION = "stop_mission";
    public static final String GOTO_POINT = "goto_point";
    public static final String SHOOT_PHOTO = "shoot_photo";
    public static final String CAMERA_CENTER = "camera_center";
    public static final String CAMERA_CHANGE_MODE = "camera_change_mode";
    public static final String TRIGGER_VIDEO = "trigger_video";
    public static final String IRC_NIGHT = "irc_night";
    public static final String IRC_DAY = "irc_day";
    public static final String IRC_AUTO = "irc_auto";
    public static final String ZOOM_PLUS = "zoom_plus";
    public static final String ZOOM_MINUS = "zoom_minus";
    public static final String FOCUS_PLUS = "focus_plus";
    public static final String FOCUS_MINUS = "focus_minus";
    public static final String FOCUS_AUTO = "focus_auto";
    public static final String CAMERA_LOCKUP = "camera_lockup";
    public static final String CAMERA_FOLLOW = "camera_follow";
    public static final String CAMERA_TRACK = "camera_track";
    public static final String MOVE_GIMBAL = "move_gimbal";
    public static final String OPEN_THROWER = "open_thrower";
    public static final String CLOSE_THROWER = "close_thrower";
    public static final String OPEN_LIGHT = "open_light";
    public static final String CLOSE_LIGHT = "close_light";
    public static final String MOVE_LIGHT = "move_light";
    public static final String NOTIFY_STATUS = "notify_status";
    public static final String LOGIN = "login";
    public static final String LOGIN_PARENT = "login_parent";
    public static final String SEND_TASK = "send_task";
    public static final String MANUAL_CONTROL = "manual_control";
    public static final String DETECT_STATUS = "detect_status";
    public static final String TRACK_STATUS = "track_status";
    public static final String VISION_LAND = "vision_land";
    public static final String SUBSCRIBE_VISION_LAND = "subscribe_vision_land";
    public static final String START_VISION_LAND = "start_vision_land";
    public static final String STOP_VISION_LAND = "stop_vision_land";
    public static final String SEND_INSTRUCTION = "send_instruction";
    public static final String NOTIFY_USER_STATUS = "notify_user_status";
    public static final String DETECTED_INFO = "detected_info";
    public static final String AIS_STATUS = "ais_status";
    public static final String SUBSCRIBE_APP_CONTROL = "subscribe_app_control";
}
