###DroneServie config
isUseDroneService=true
deviceUseRTCP=true
#Timeout of connecting drones.Unit is second.
connectTimeout=30
#Session idle time.Unit is second.
idleTime=600
#Session timeout.Unit is second.
sessionTimeout=30
#The time span of checking drones.Unit is second.
checkDroneTime=3000
#The systemId of gcs.
gcsSystemId=255

###CommandService Config
#cmdTcpMode=true
#cmdTcpPort=60000
#cmdUdpMode=true
#cmdUdpPort=8203
#The time span of sending heartbeat.Unit is millisecond.
#tsSendHeartbeat=2000
#isTcpServerSendHeartbeat=true
#isUdpServerSendHeartbeat=false


#RabbitMQ Config
Host=127.0.0.1
Port=5672
Username=guest
Password=guest
VirtualHost=/
isUseRabbitService=true
TO_EXCHANGE_NAME=simulator_send
FROM_EXCHANGE_NAME=simulator_recv

#Entity Config
#Drone1
deviceId1=1
deviceName1=wrj-001
deviceType1=0
deviceIp1=127.0.0.1
devicePort1=5760
#Drone2
deviceId2=2
deviceName2=wrj-002
deviceType2=0
deviceIp2=127.0.0.1
devicePort2=5760